version: '3.8'
services:

    # Application
    app_searchable:
        build:
            context: .
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database_searchable"
        networks:
            - searchable_network
    # Web Server
    web_searchable:
        build:
            context: .
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app_searchable"
        ports:
            - 8867:82
        networks:
            - searchable_network
    # Database
    database_searchable:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        networks:
            - searchable_network
volumes:
    dbdata:

networks:
  searchable_network:
    name: searchable_network
